### ISSUE TITLE
Compile failure in RHEL7

### ISSUE THREAD

**Issue by gharber** [brettbode/GamessQ#6]
configure is happy but
make[1]: Entering directory `/usr/local/gamessq-1.2.1/src'
g++ -DPACKAGE_NAME=\"GamessQ\" -DPACKAGE_TARNAME=\"gamessq\" -DPACKAGE_VERSION=\"1.2.1\" -DPACKAGE_STRING=\"GamessQ\ 1.2.1\" -DPACKAGE_BUGREPORT=\"MMP.Guy@gmail.com\" -DPACKAGE_URL=\"\" -DPACKAGE=\"gamessq\" -DVERSION=\"1.2.1\" -I.    -I/usr/lib64/wx/include/gtk2-unicode-release-2.8 -I/usr/include/wx-2.8 -D_FILE_OFFSET_BITS=64 -D_LARGE_FILES -D__WXGTK__ -pthread -DDATA_DIR='"/usr/local/share/gamessq"' -g -O2 -MT resources.o -MD -MP -MF .deps/resources.Tpo -c -o resources.o resources.cpp
resources.cpp: In function ‘wxBitmap GetGamessQBitmap(wxString)’:
resources.cpp:32:56: error: invalid initialization of reference of type ‘wxStandardPaths&’ from expression of type ‘wxStandardPathsBase’
     wxStandardPaths & gStdPaths = wxStandardPaths::Get();
                                                        ^
resources.cpp: In function ‘wxIcon GetGamessQIcon()’:
resources.cpp:83:56: error: **invalid initialization of reference of type ‘wxStandardPaths&’** from expression of type ‘wxStandardPathsBase’
     wxStandardPaths & gStdPaths = wxStandardPaths::Get();
                                                        ^
make[1]: *** [resources.o] Error 1
make[1]: Leaving directory`/usr/local/gamessq-1.2.1/src'
make: **\* [all-recursive] Error 1

**Comment by brettbode** [comment]
Hello,
   This is a compatibility issue with wxWidgets 2.8. I have restored the ability to build with wx2.8 in my latest checkin. You can grab a tar file of that code in prerelease form at:
https://uofi.box.com/s/7i21an0jrraewv2qnbfhw2w4onrqv4gr

Brett

**Comment by brettbode** [comment]
I believe this issue is resolved though I no longer test against wx 2.8. I will note that CentOS 7.7 ELEP has packages for wx 3 so please choose the wxgtk3 packages rather than the wxgtk (which are v2.8) packages.
